name = "csharp"
title = "C#/.NET"
toc_landing_pages = [
  "/fundamentals/connection",
  "/fundamentals/crud",
  "/usage-examples",
]

intersphinx = [
  "https://www.mongodb.com/docs/manual/objects.inv",
  "https://www.mongodb.com/docs/drivers/objects.inv",
  "https://www.mongodb.com/docs/atlas/objects.inv",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]
driver-long = "MongoDB .NET/C# Driver"
driver-short = ".NET/C# Driver"
lang-framework = ".NET/C#"
language = "C#"
docs-branch = "master"                                                                                                         # always set this to the docs branch (i.e. master, 1.7, 1.8, etc.)
version-number = "2.17"                                                                                                        # always set this to the driver branch (i.e. 1.7.0, 1.8.0, etc.)
version = "v{+version-number+}"
example = "https://raw.githubusercontent.com/mongodb/docs-csharp/{+docs-branch+}/source/includes/usage-examples/code-examples"
stable-api = "Stable API"
api-root = "https://mongodb.github.io/mongo-csharp-driver/{+version-number+}/apidocs/html"
allow-insecure-tls = "Specifies whether to relax TLS constraints as much as possible. This can include allowing invalid certificates or hostname mismatches."
app-name = "The app name the driver passes to the server in the client metadata as part of the connection handshake. The server prints this value to the MongoDB logs once the connection is established. The value is also recorded in the slow query logs and profile collections."
compressors = "The preferred compression types, in order, for wire-protocol messages sent to or received from the server. The driver uses the first of these compression types that the server supports. See :ref:`csharp-network-compression` for more information."
connect-timeout = "The length of time the driver tries to establish a single TCP socket connection to the server before timing out. Specifying ``0`` disables the connection timeout."
direct-connection = "Specifies whether to force dispatch **all** operations to the host specified in the connection URI."
heartbeat-interval = "The interval between regular server-monitoring checks."
load-balanced = "Specifies whether the driver is connecting to a load balancer."
local-threshold = "The latency window for server eligibility. If a server's round trip takes longer than the fastest server's round-trip time plus this value, the server isn't eligible for selection. Specifying ``0`` selects the fastest eligible server."
max-connecting = "The greatest number of connections a driver's connection pool may be establishing concurrently."
max-connection-idle-time = "The length of time a connection can be idle before the driver closes it. Specifying ``0`` means no maximum."
max-connection-pool-size = "The greatest number of clients or connections the driver can create in its connection pool. This count includes connections in use."
min-connection-pool-size = "The number of connections the driver should create and keep in the connection pool even when no operations are occurring. This count includes connections in use."
read-concern = "The client's default read concern. See :ref:`read concern <read-concern>` for more information."
read-preference = "The client's default read preference (excluding tags). See :ref:`read preference <read-preference>` for more information."
replica-set-name = "The name of the replica set to connect to."
retry-reads = "Enables retryable reads."
retry-writes = "Enables retryable writes."
server-selection-timeout = "The length of time the driver tries to select a server before timing out."
socket-timeout = "The length of time the driver tries to send or receive on a socket before timing out. Specifying ``0`` means no timeout."
srv-max-hosts = "The greatest number of SRV results to randomly select when initially populating the seedlist or, during SRV polling, adding new hosts to the topology. Specifying ``0`` means no maximum."
use-tls = "Specifies whether to require TLS for connections to the server. If you use a scheme of ``\"mongodb+srv\"``, or specify other ``tls``-prefixed options, this option defaults to ``true``."
write-concern = "The default write concern ``\"w\"`` field for the client. See :ref:`write concern <wc-j>` for more information."
wait-queue-timeout = "The length of time the driver tries to check out a connection from a server's connection pool before timing out. Specifying ``0`` means no timeout."

