name: add-redirects
on:
  pull_request_target:
jobs:
  get-redirects-renamed:
    name: Get Renamed Files
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Get renamed files
        id: changed-files
        # pin to a specific commit to ensure stability
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c
        with:
          include_all_old_new_renamed_files: true
          files: |
            source/**
            **.txt
      - name: Parse renamed files
        id: renamed-files
        if: steps.changed-files.outputs.renamed_files_count > 0
        env:
          RENAMED_FILES: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
        run: |
          renamed_redirects=""
          for file in $RENAMED_FILES; do
            old=$(echo "$file" | cut -d',' -f1)
            old="${old#source}"
            old="${old%.txt}"
            new=$(echo "$file" | cut -d',' -f2)
            new="${new#source}"
            new="${new%.txt}"
            #single quotes = ${var} rendered literally; double quotes = $var interpreted
            renamed_redirects+='\n- [ ] Did you add redirects for renamed files?\n<li>[*-master]: ${prefix}/${version}'"$old"'/ -> ${base}/${version}'"$new"'/</li>'
          done
          echo "redirects=${renamed_redirects}" >> "$GITHUB_OUTPUT"
      - name: Update the PR Description
        uses: MongoCaleb/pr-description-action@master
        with:
          content: "${{ steps.renamed-files.outputs.redirects }}\n- [ ] Did you add redirects for deleted files?"
          token: ${{ secrets.GITHUB_TOKEN }}
