name: add-redirects
on:
  pull_request:
jobs:
  get-redirects-renamed:
    name: Get Renamed Files
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Update the PR Description
        uses: MongoCaleb/pr-description-action@master
        with:
          content: "auth test"
          token: ${{ secrets.GITHUB_TOKEN }}
