name: add-redirects
on:
  pull_request:
    paths:
      - "source/**"
jobs:
  get-redirects:
    name: Get Renamed Files
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        # pin to a specific commit to ensure stability
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c
        with:
          include_all_old_new_renamed_files: true
          files: |
            **.txt
      - name: Get renamed files
        id: renamed-files
        if: steps.changed-files.outputs.renamed_files_count > 0
        env:
          RENAMED_FILES: ${{ steps.changed-files.outputs.all_old_new_renamed_files }}
        run: |
          new_redirects=""
          for file in $RENAMED_FILES; do
            old=$(echo "$file" | cut -d',' -f1)
            old="${old#source}"
            old="${old%.txt}/"
            new=$(echo "$file" | cut -d',' -f2)
            new="${new#source}"
            new="${new%.txt}/"
            new_redirects+="<li>[*-master]: \$\{prefix\}/\$\{version\}$old -> \$\{base\}/\$\{version\}$new</li>"
          done
          echo $new_redirects
          echo "redirects_list=${new_redirects}" >> "$GITHUB_OUTPUT"

      - name: Update PR Description
        uses: MongoCaleb/pr-description-action@master
        with:
          content: " ${{ steps.renamed-files.outputs.redirects_list }}"
          token: ${{ secrets.GITHUB_TOKEN }}
